version: '3.3'

volumes:
  postgres_data:
    driver: local

services:
  library-db:
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: library-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  library-api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - library-db
    restart: on-failure
    tty: true
    stdin_open: true
