server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

web:
  cors:
    allowed-origins: http://localhost:3000, http://127.0.0.1:3000, http://localhost:5173, http://127.0.0.1:5173
    allowed-methods: POST, PUT, DELETE, GET, HEAD, OPTIONS, PATCH
    allowed-headers: Content-Type, X-Requested-With, Accept, Authorization, Origin, Access-Control-Request-Method,
      Access-Control-Request-Headers, X-Reset-Token
jwt:
  secret-key: eAW+O7sUshT4+XKHOIIsZxObn+wu4OcT8FsWwaU8ldw=
  token-expiration-days: 2