server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgres://library-db:5432/library-db
    username: postgres
    password: admin
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect